ARG base_image=ubuntu:24.04

FROM ${base_image}

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -u -y install lsb-release python3 binutils python3-venv python3-pip wget git bash-completion vim yq jq \
    && apt-get -qq purge && apt-get -qq clean && rm -rf /var/lib/apt/lists/*

RUN pip install --break-system-packages jupyterlab
COPY ./pyproject.toml ./README.md ./MANIFEST.in /src/
COPY ./amscrot /src/amscrot
COPY ./tools /src/tools
RUN python3 -m pip install --break-system-packages --no-cache-dir "/src[all]"
